# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'CircleLoading' do
pod 'MBProgressHUD', '~> 0.9.2'
pod 'Masonry', '~> 0.6.4'
end

