# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target '引导页动画一' do

end

target '引导页动画一Tests' do

end

